"""empty message

Revision ID: 7cbca2567244
Revises: 859443de4d46
Create Date: 2022-01-27 17:42:43.061984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbca2567244'
down_revision = '859443de4d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_package_author'), 'package', ['author'], unique=False)
    op.create_index(op.f('ix_package_downloads_total'), 'package', ['downloads_total'], unique=False)
    op.create_index(op.f('ix_package_likes'), 'package', ['likes'], unique=False)
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.drop_index(op.f('ix_package_likes'), table_name='package')
    op.drop_index(op.f('ix_package_downloads_total'), table_name='package')
    op.drop_index(op.f('ix_package_author'), table_name='package')
    # ### end Alembic commands ###
